### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by ievarau** [AcaDemIQ/mcot-kernel#10]
Dear authors,

I just want to let you know that I encountered a segmentation fault error for some of my bigger datasets (40000, 80000 sequences). Produced results are then partial. With datasets with 10000 or less sequences the tools seems to be working well.

Best,
Ieva

**Comment by parthian-sterlet** [comment]
Formally, the size of the dataset is not limited, dynamic memory is used. I have never tested such big sizes above 10000. 
In a few days, new version of mcot.cpp  will be available on github.
New version
1) takes motifs from [Hocomoco12](https://hocomoco12.autosome.org/H12CORE) (mm & hg hocomoco11 full collections are deleted, hocomoco 11 core collections are preserved, see [Hocomoco 11](https://hocomoco11.autosome.org/downloads_v11))
2) takes partner motifs PFMs/PWMs and their thresholds from binary files from disk, old version stores them all in memory.
New mcot.cpp requires substantially less memory than the old version, but new version is slightly slower. Let we see how this new version treats big dataset sizes

**Comment by parthian-sterlet** [comment]
I wrote at github
` DNA sequences of ChIP-seq peaks in fasta format, a minimum recommended number of peaks is about 300-500, the maximum number is not restricted, however 5000-10000 or higher number of peaks requires a higher computation time than several thousands of peaks, hence about 1000-2000 peaks are enough. `
Actual reason is not only computation time, we checked in [Frontiers paper, Figure S3](https://www.frontiersin.org/articles/10.3389/fpls.2022.938545/full) that an anchor motif enrichment is strong enough only for the high-scoring ChIP-seq peaks (about 1000), but let we test a new version. 
If the issue persists, I can propose only a preliminary filtration of a dataset by an anchor motif content

**Comment by parthian-sterlet** [comment]
Dear Ieva, you can find the new MCOT version on its unofficial site, https://github.com/parthian-sterlet/mcot-kernel.
New hocomoco motifs libraries are included. The main essential change in mcot.cpp refers to the libraries of partner motifs , see the parameter argv[3], another one argv[6] is changed only formally, see [example command line](https://github.com/parthian-sterlet/mcot-kernel/blob/master/run/command_line_many) and [readme](https://github.com/parthian-sterlet/mcot-kernel/tree/master#command-line-arguments). The memory requirements have been significantly reduced. I hope, this supports much larger dataset sizes.

**Comment by ievarau** [comment]
Thank you very much for the information!
